// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: protoPkg/human.proto

package protoPkg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Human struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *Human) Reset() {
	*x = Human{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoPkg_human_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Human) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Human) ProtoMessage() {}

func (x *Human) ProtoReflect() protoreflect.Message {
	mi := &file_protoPkg_human_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Human.ProtoReflect.Descriptor instead.
func (*Human) Descriptor() ([]byte, []int) {
	return file_protoPkg_human_proto_rawDescGZIP(), []int{0}
}

func (x *Human) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Human) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_protoPkg_human_proto protoreflect.FileDescriptor

var file_protoPkg_human_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x6b, 0x67, 0x2f, 0x68, 0x75, 0x6d, 0x61, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x05, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoPkg_human_proto_rawDescOnce sync.Once
	file_protoPkg_human_proto_rawDescData = file_protoPkg_human_proto_rawDesc
)

func file_protoPkg_human_proto_rawDescGZIP() []byte {
	file_protoPkg_human_proto_rawDescOnce.Do(func() {
		file_protoPkg_human_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoPkg_human_proto_rawDescData)
	})
	return file_protoPkg_human_proto_rawDescData
}

var file_protoPkg_human_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protoPkg_human_proto_goTypes = []interface{}{
	(*Human)(nil), // 0: Human
}
var file_protoPkg_human_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoPkg_human_proto_init() }
func file_protoPkg_human_proto_init() {
	if File_protoPkg_human_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoPkg_human_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Human); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoPkg_human_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoPkg_human_proto_goTypes,
		DependencyIndexes: file_protoPkg_human_proto_depIdxs,
		MessageInfos:      file_protoPkg_human_proto_msgTypes,
	}.Build()
	File_protoPkg_human_proto = out.File
	file_protoPkg_human_proto_rawDesc = nil
	file_protoPkg_human_proto_goTypes = nil
	file_protoPkg_human_proto_depIdxs = nil
}
